### ISSUE TITLE
Make Prism-specific colours specific to Prism

### ISSUE THREAD

**Issue by arangas** [dlecina/StayPuft#10]
In commit 2bbe3ba41065f486ee35c55dc0216d6160b8362e, colours and other tweaks were specified in the CSS for `<code>`, `<tt>`, and `<pre>`. It looks like this was for improved rendering with Prism. The problem is that if these tags are used for anything else (I particularly mean `<pre>`) then the rendered colour is effectively white on white.

I was thinking about prefixing these changes with something like `code[class*="language-"], pre[class*="language-"]`. What do you think about this and would you like a PR?

**Comment by dlecina** [comment]
I don't seem to be having this issue (see http://davidlecina.com/blog/codepretest/). Can you provide any examples?

**Comment by arangas** [comment]
Ah never mind. I added another library which caused confusion, and is why you can't repro. Apologies!
