### ISSUE TITLE
Is there a fold mode for the homepage?

### ISSUE THREAD

**Issue by d0u9** [dlecina/StayPuft#13]
I am wondering that is there a folded mode for the homepage? Displaying the full content on homepage makes a mess sense.

Thanks for your awesome work!

**Comment by dlecina** [comment]
I'm not sure what you mean. If you want to show an excerpt of the posts on your index, instead of the full post, please try reverting the changes in 9e90d4e631f509be78cf4b5805843b720eaade3f. If you have any questions, I'll be happy to help.

**Comment by d0u9** [comment]
Yes, I do mean excerpt. Thanks a lot!
