### ISSUE TITLE
The in-site search function seems not work. 

### ISSUE THREAD

**Issue by d0u9** [dlecina/StayPuft#14]
Hi, I found that the in-site search  function doesn't work properly even in your [Demo](http://davidlecina.com/blog/).

**Comment by dlecina** [comment]
It doesn't show static pages, but it should work for normal posts. Try searching 'Portal'.

The theme uses the Ghosthunter plugin, which is far from perfect. The Ghost guys are supposed to be developing their own search function, so I'm waiting for them to finish it. When it's ready, I'll replace the current plugin.

**Comment by d0u9** [comment]
Well, It's seems that ghosthunter doesn't support Chinese language...

**Comment by Engine-X** [comment]
For me sarching also doesn't work.

**Comment by arangas** [comment]
To keep updated on the search feature in Ghost, subscribe to https://github.com/TryGhost/Ghost/issues/5321

**Comment by dlecina** [comment]
GhostHunter is now updated to work with the Ghost API and search should work (as long as the API is enabled in the Labs section).

Static page support: https://github.com/jamalneufeld/ghostHunter#include-static-pages-in-the-search

Chinese language support: no idea. It is up to GhostHunter to provide it. If it still does not have support, open up an issue in their repo. If it is ever added, feel free to open a new issue here to request an update. I will be closing this one for the time being.
