### ISSUE TITLE
Can I use this theme on the Wordpress?

### ISSUE THREAD

**Issue by zhangity** [dlecina/StayPuft#16]
I really like your theme and thank you for your share ,but my bolg is wordpress not ghost ,could I use this wonderful theme on it ? Thanks:)

**Comment by dlecina** [comment]
Hi zhangity,

I'm afraid Ghost themes are much too different from Wordpress themes to be used interchangeably. I would have to recreate the entire theme for Wordpress, and I have no plans to do so.

Wordpress has amazing theme support, though, so I'm sure you'll be able to find an even better looking theme for it. Best of luck!
