### ISSUE TITLE
Support for Ghost 1.x

### ISSUE THREAD

**Issue by afedulov** [dlecina/StayPuft#28]
I really like your theme and have been using it for a long time. There are some breaking changes in Ghost 1.x . Do you plan to adjust to those?

**Comment by dlecina** [comment]
Yes. I will try to find some time to update the theme soon™

**Comment by dlecina** [comment]
The theme is now updated. Sorry it took so long, I just couldn't find the time and the backlog got larger and larger... I ended up pretty much having to rewrite the whole thing.

![Please understand](https://media.giphy.com/media/DwpavZaqZHExG/giphy.gif)

Anyway, it's here now, and personally I think it's better than ever. [Let me know what you think!](https://davidlecina.com/blog/staypuft-theme-update-2-2-1/)
